language: ruby
rvm:
  - 2.4

env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
  matrix:
    - DB=mysql

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - TRAVIS=true bundle exec rspec spec/

gemfile:
  - gemfiles/Gemfile.rails-4.2.x
  - Gemfile

before_script:
  - mysql -e 'create database recruiter_test'

sudo: false
